## Tipi di dato

#### Tipi atomici

I tipi atomici (o tipi primitivi) sono i tipi di dati più semplici e fondamentali, utilizzati per rappresentare valori di base. Ecco una descrizione dei tipi atomici principali:
<ul>
    <li>int (Intero): Rappresenta numeri interi, positivi o negativi, senza parte decimale. Esempio: 42, -7, 0;</li>
    <li>float (Virgola mobile): Rappresenta numeri reali con parte decimale, anche espressi in notazione scientifica. Esempio: 3.14, -0.001, 2e3 (che rappresenta 2×1032×103);</li>
    <li>complex (Complesso): Rappresenta numeri complessi, con una parte reale e una parte immaginaria. La parte immaginaria è indicata con j. Esempio: 3 + 4j, -2 - 5j;</li>
    <li>bool (Booleano): Rappresenta valori logici True o False. È una sotto-classe degli interi, in cui True corrisponde a 1 e False a 0;</li>
    <li>str (Stringa): Rappresenta sequenze di caratteri, utilizzate per memorizzare testo. Le stringhe sono immutabili, il che significa che non possono essere modificate dopo la creazione. Esempio: "c", 'abab';</li>
    <li>bytes: Rappresenta sequenze immutabili di byte, utilizzate per gestire dati binari. Ogni elemento è un numero intero tra 0 e 255. Esempio: b'hello';</li>
    <li>bytearray: Simile a bytes, ma mutabile, permettendo la modifica dei byte dopo la creazione. Utilizzato principalmente per manipolazioni binarie quando è necessaria mutabilità;</li>
    <li>NoneType: Ha un solo valore possibile, None, che rappresenta l'assenza di un valore o un valore nullo;</li>
</ul>

In [8]:
## int

n = 1
print(n)
print(f"Bit di n: {n.bit_length()}")
print(f"Bytes di n: {n.to_bytes(2, 'big')}")

1
Bit di n: 1
Bytes di n: b'\x00\x01'


In [11]:
## float
f = 3.1415

print(f)
print("Rappresentazione frazionaria: {f.as_integer_ratio()}")


3.1415
Rappresentazione frazionaria: {f.as_integer_ratio()}


In [15]:
## complex

c = 1 + 1j
print(c)

print(f"Parte reale: {c.real}")
print(f"Parte immaginaria: {c.imag}")
print(f"Coniugato: {c.conjugate()}")

(1+1j)
Parte reale: 1.0
Parte immaginaria: 1.0
Coniugato: (1-1j)


In [17]:
## bool
v = True

print(f"Intero equivalente: {int(v)}")
print(f"Stringa equivalente: {str(v)}")

Intero equivalente: 1
Stringa equivalente: True


In [23]:
## str
t = "Assioma"
print(t)
print(f"Maiuscolo: {t.upper()}")
print(f"Ricerca str: {t.find("s")}")
print(f"Sostiuzione: {t.replace("Assioma", "Concetto Primitivo")}")

Assioma
Maiuscolo: ASSIOMA
Ricerca str: 1
Sostiuzione: Concetto Primitivo


In [26]:
## bytes
dati = b'Assioma'

print(dati)
print(f"Decodificato: {dati.decode("utf-8")}")

print(f"Rappresentazione esadecimale {dati.hex()}")

b'Assioma'
Decodificato: Assioma
Rappresentazione esadecimale 417373696f6d61


In [28]:
## byte array
dati = bytearray(b'Assioma')

print(dati)
dati.append(33) # aggiunge '!'

print(dati)

bytearray(b'Assioma')
bytearray(b'Assioma!')


In [30]:
## none
v = None

print(v)

v is None

None


True

#### Tipi strutturati
I tipi strutturati o strutture di dati. sono tipi che consentono di memorizzare e organizzare più valori e includono:

<ul>
    <li>Liste (list): Collezioni mutabili e ordinate di elementi, che possono contenere tipi diversi;</li>
    <li>Tuple (tuples): Collezioni ordinate ma immutabili di elementi, simili alle liste ma non modificabili dopo la creazione;</li>
    <li>Dizionari (dict): Collezioni di coppie chiave-valore, in cui ogni chiave è unica e mappa a un valore;</li>
    <li>Set (set): Collezioni non ordinate e non indicizzate di elementi unici;</li>
    <li>Frozen set (frozenset): Versione immutabile dei set;</li>
</ul>

In [55]:
## list

temperature = [21.5, 22.0, 19.8, 20.4, 22.1, 21.7, 20.9]
print(f"Temperature: {temperature}")
temperature.append(23.2)
print(f"Temperature: {temperature}")

temp_massima = max(temperature)
temp_minima = min(temperature)

print(f"Temperature massima: {temp_massima}")
print(f"Temperature minima: {temp_minima}")

Temperature: [21.5, 22.0, 19.8, 20.4, 22.1, 21.7, 20.9]
Temperature: [21.5, 22.0, 19.8, 20.4, 22.1, 21.7, 20.9, 23.2]
Temperature massima: 23.2
Temperature minima: 19.8


In [33]:
## tuple
coordinate = (10.0, 20.0, 10.0)

print("Volte in cui compare il 10.0: ", coordinate.count(10.0))
print("Indice di 20.0: ", coordinate.index(20.0))

Volte in cui compare il 10.0:  2
Indice di 20.0:  1


In [53]:
## dict
import scipy

constant = {'pi': scipy.constants.pi, 'g': scipy.constants.G}

print(constant['pi'])

print("Coppie chiave-valore: ", list(constant.items()))

constant.update({"protonMass":scipy.constants.proton_mass})
print(constant['protonMass'])

3.141592653589793
Coppie chiave-valore:  [('pi', 3.141592653589793), ('g', 6.6743e-11)]
1.67262192369e-27


In [42]:
## set
primi = {1, 2, 3, 5, 7, 11, 13, 17, 19}

print(primi)

primi.add(29)
print(primi)

primi.discard(19)
primi.discard(29)
print(primi)

add_primi = {19, 29}
u = primi.union(add_primi)
print(u)

{1, 2, 3, 5, 7, 11, 13, 17, 19}
{1, 2, 3, 5, 7, 11, 13, 17, 19, 29}
{1, 2, 3, 5, 7, 11, 13, 17}
{1, 2, 3, 5, 7, 11, 13, 17, 19, 29}


In [56]:
elementi_essenziali = frozenset(["carbonio", "idrogeno", "ossigeno", "azoto", "fosforo", "zolfo"])
elementi_campione = {"carbonio", "ferro", "ossigeno", "calcio", "azoto"}


elementi_presenti = elementi_essenziali.intersection(elementi_campione)
print("Elementi essenziali presenti nel campione:", elementi_presenti)

elementi_mancanti = elementi_essenziali.difference(elementi_campione)
print("Elementi essenziali mancanti nel campione:", elementi_mancanti)

nessun_elemento_essenziale = elementi_essenziali.isdisjoint(elementi_campione)
print("Il campione non contiene elementi essenziali?", nessun_elemento_essenziale)

Elementi essenziali presenti nel campione: frozenset({'azoto', 'carbonio', 'ossigeno'})
Elementi essenziali mancanti nel campione: frozenset({'idrogeno', 'zolfo', 'fosforo'})
Il campione non contiene elementi essenziali? False


#### Numpy Array

Descrizione: NumPy è una libreria fondamentale per il calcolo scientifico in Python. Gli array NumPy sono strutture multidimensionali che supportano operazioni vettoriali efficienti, ideali per il calcolo numerico e l’analisi dei dati.

In [74]:
import numpy as np

array_1d = np.array([1,2,3,4,5])
print(array_1d)
print(type(array_1d))
print(id(array_1d))


array_1d = array_1d ** 2
print("\n", array_1d)
print(id(array_1d)) ## numpy.ndarray sono quindi immutabili

array_2d = np.array([[1,2], [2,1]])
print("\n", array_2d)

det = np.linalg.det(array_2d) # calcolo del determinante di un array 2 * 2
print("\n", det)

sum_colonne = array_2d.sum(axis=0) # somma colonne
print("\n", sum_colonne)

media = array_2d.mean() # calcolo della media
print("\n", media)

molt_lambda = array_2d * 4 # moltiplicazione per uno scalare
print("\n", molt_lambda)

[1 2 3 4 5]
<class 'numpy.ndarray'>
137060864458064

 [ 1  4  9 16 25]
137060997344848

 [[1 2]
 [2 1]]

 -2.9999999999999996

 [3 3]

 1.5

 [[4 8]
 [8 4]]


#### SciPy Sparse Matrices

La libreria SciPy offre supporto per matrici sparse, ossia matrici che contengono principalmente zeri, per ottimizzare la memoria e le prestazioni. Vengono usate in ambiti come l'algebra lineare, il machine learning, e il trattamento di dati molto grandi, come nelle reti di connessioni o grafi.

In [76]:
from scipy.sparse import csr_matrix as matrix

matrice_densa = np.array([[0,0,3],[4,0,0],[0,0,1]])
print(matrice_densa)

matrice_sparsa = matrix(matrice_densa)
print(matrice_sparsa)

[[0 0 3]
 [4 0 0]
 [0 0 1]]
<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 2)	3
  (1, 0)	4
  (2, 2)	1


#### SymPy per il calcolo simbolico

SymPy è una libreria per il calcolo simbolico, usata per la manipolazione algebrica, l'integrazione e la risoluzione di equazioni. È utile per algebra lineare simbolica, derivate, integrali e risoluzione di equazioni.

In [85]:
import sympy as sp

x = sp.symbols("x")
print(type(x))
print(id(x))

fx = x**3 + 2*x**2 + x + 5 # definizione di una funzione
print("\nf(x) = ", fx)

fpx = sp.diff(fx, x)
print("\nf'(x) = ", fpx)

<class 'sympy.core.symbol.Symbol'>
137060678308208

f(x) =  x**3 + 2*x**2 + x + 5

f'(x) =  3*x**2 + 4*x + 1


#### Pandas Dataset

Pandas è una libreria potente per l’analisi e la manipolazione dei dati. I DataFrame sono strutture tabellari che permettono di analizzare, filtrare e trasformare grandi quantità di dati con facilità, rendendoli ideali per dataset strutturati.

In [106]:
import pandas as pd

dati = {
    "id_stazione": ["stazione_1", "stazione_1", "stazione_1", "stazione_2", "stazione_2", "stazione_2"],
    "data_ora": pd.to_datetime([
        "2024-10-26 08:00:00",
        "2024-10-26 12:00:00",
        "2024-10-26 16:00:00",
        "2024-10-26 08:00:00",
        "2024-10-26 12:00:00",
        "2024-10-26 16:00:00"
    ]),
    "temperatura_C": [18.5, 21.3, 19.8, 19.1, 22.0, 20.5],
    "umidità_relativa": [55, 50, 53, 60, 55, 58],
    "co2_ppm": [400, 405, 398, 390, 395, 389]
}

df = pd.DataFrame(dati)
print(df)
print("\n", type(df))

stats = df.describe()
print(stats)

df_filtred = df[df["temperatura_C"] > 20]
print("\n\nDataFrame filtrato: ", df_filtred)

media_per_stazione = df.groupby("id_stazione").mean()
print("\n\nMedia per stazione:", media_per_stazione)

  id_stazione            data_ora  temperatura_C  umidità_relativa  co2_ppm
0  stazione_1 2024-10-26 08:00:00           18.5                55      400
1  stazione_1 2024-10-26 12:00:00           21.3                50      405
2  stazione_1 2024-10-26 16:00:00           19.8                53      398
3  stazione_2 2024-10-26 08:00:00           19.1                60      390
4  stazione_2 2024-10-26 12:00:00           22.0                55      395
5  stazione_2 2024-10-26 16:00:00           20.5                58      389

 <class 'pandas.core.frame.DataFrame'>
                  data_ora  temperatura_C  umidità_relativa     co2_ppm
count                    6        6.00000          6.000000    6.000000
mean   2024-10-26 12:00:00       20.20000         55.166667  396.166667
min    2024-10-26 08:00:00       18.50000         50.000000  389.000000
25%    2024-10-26 09:00:00       19.27500         53.500000  391.250000
50%    2024-10-26 12:00:00       20.15000         55.000000  396.500

#### JSON

JSON è un formato leggero per lo scambio di dati, comunemente utilizzato per la comunicazione tra client e server. In Python, i dati JSON possono essere gestiti come dizionari o liste, rendendoli ideali per strutture dati gerarchiche e leggere.

In [91]:
import json

j_data = '''{
  "esperimento": "Monitoraggio Ambientale",
  "data_inizio": "2024-10-26",
  "data_fine": "2024-11-02",
  "stazioni": [
    {
      "id": "stazione_1",
      "nome": "Stazione Nord",
      "coordinati": {
        "latitudine": 45.1234,
        "longitudine": 12.5678
      },
      "misurazioni": [
        {
          "timestamp": "2024-10-26T08:00:00Z",
          "temperatura_C": 18.5,
          "umidità_relativa": 55,
          "co2_ppm": 400
        },
        {
          "timestamp": "2024-10-26T12:00:00Z",
          "temperatura_C": 21.3,
          "umidità_relativa": 50,
          "co2_ppm": 405
        }
      ]
    },
    {
      "id": "stazione_2",
      "nome": "Stazione Sud",
      "coordinati": {
        "latitudine": 44.9876,
        "longitudine": 11.8765
      },
      "misurazioni": [
        {
          "timestamp": "2024-10-26T08:00:00Z",
          "temperatura_C": 19.1,
          "umidità_relativa": 60,
          "co2_ppm": 390
        },
        {
          "timestamp": "2024-10-26T12:00:00Z",
          "temperatura_C": 22.0,
          "umidità_relativa": 55,
          "co2_ppm": 395
        }
      ]
    }
  ]
}'''

print(j_data)

print("\n", type(j_data)) #str

{
  "esperimento": "Monitoraggio Ambientale",
  "data_inizio": "2024-10-26",
  "data_fine": "2024-11-02",
  "stazioni": [
    {
      "id": "stazione_1",
      "nome": "Stazione Nord",
      "coordinati": {
        "latitudine": 45.1234,
        "longitudine": 12.5678
      },
      "misurazioni": [
        {
          "timestamp": "2024-10-26T08:00:00Z",
          "temperatura_C": 18.5,
          "umidità_relativa": 55,
          "co2_ppm": 400
        },
        {
          "timestamp": "2024-10-26T12:00:00Z",
          "temperatura_C": 21.3,
          "umidità_relativa": 50,
          "co2_ppm": 405
        }
      ]
    },
    {
      "id": "stazione_2",
      "nome": "Stazione Sud",
      "coordinati": {
        "latitudine": 44.9876,
        "longitudine": 11.8765
      },
      "misurazioni": [
        {
          "timestamp": "2024-10-26T08:00:00Z",
          "temperatura_C": 19.1,
          "umidità_relativa": 60,
          "co2_ppm": 390
        },
        {
          "timest

In [95]:
data = json.loads(j_data) # conversione da str a json

print(data)
print("\n", type(data))

{'esperimento': 'Monitoraggio Ambientale', 'data_inizio': '2024-10-26', 'data_fine': '2024-11-02', 'stazioni': [{'id': 'stazione_1', 'nome': 'Stazione Nord', 'coordinati': {'latitudine': 45.1234, 'longitudine': 12.5678}, 'misurazioni': [{'timestamp': '2024-10-26T08:00:00Z', 'temperatura_C': 18.5, 'umidità_relativa': 55, 'co2_ppm': 400}, {'timestamp': '2024-10-26T12:00:00Z', 'temperatura_C': 21.3, 'umidità_relativa': 50, 'co2_ppm': 405}]}, {'id': 'stazione_2', 'nome': 'Stazione Sud', 'coordinati': {'latitudine': 44.9876, 'longitudine': 11.8765}, 'misurazioni': [{'timestamp': '2024-10-26T08:00:00Z', 'temperatura_C': 19.1, 'umidità_relativa': 60, 'co2_ppm': 390}, {'timestamp': '2024-10-26T12:00:00Z', 'temperatura_C': 22.0, 'umidità_relativa': 55, 'co2_ppm': 395}]}]}

 <class 'dict'>
